version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - 3000:3000

  web-tests:
    image: vidly_web
    volumes:
      - ./frontend:/app
    command: npm test

  api:
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    environment:
      DB_URL: mongodb://db/vidly
    
    command: ./docker-entrypoint.sh
    # command: ./wait-for db:27017 migrate-mongo up && npm start

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly: